# -*- coding: utf-8 -*-
"""PRTM-protein_mass_calculator

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pXw6S_xJV0Uhfj3Ze3bbgkiRC5hq5T1m
"""

def protein_mass_calculator(protein_string): 

  protein_mass_table = { "A" : 71.03711, "C" : 103.00919, "D" : 115.02694, "E" : 129.04259, "F" : 147.06841, 
                        "G" : 57.02146, "H" : 137.05891, "I" : 113.08406, "K" : 128.09496,
                        "L" : 113.08406, "M" : 131.04049, "N" : 114.04293, "P" : 97.05276,
                        "Q" : 128.05858, "R" : 156.10111, "S" : 87.03203, "T" : 101.04768, 
                        "V" : 99.06841, "W" : 186.07931, "Y" : 163.06333, }
  liste = []
  for i in protein_string: 

    if i in protein_mass_table.keys(): 
      liste.append(protein_mass_table[i])

  return round(sum(liste),3)  #result is rounded to  decimal points